//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.ABAS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABAS.GetAffiliationDataSoap")]
    public interface GetAffiliationDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Faculty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Faculty(string FacultyName, string RegistrationNo, string AadhaarNo, string CollegeID, string DepartmentID, string Designation, string Address, string City, string State, string Gender, string Dob, string MobileNo, string Email, string Pincode, string Type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetAffiliationDataSoapChannel : UAAAS.ABAS.GetAffiliationDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAffiliationDataSoapClient : System.ServiceModel.ClientBase<UAAAS.ABAS.GetAffiliationDataSoap>, UAAAS.ABAS.GetAffiliationDataSoap {
        
        public GetAffiliationDataSoapClient() {
        }
        
        public GetAffiliationDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAffiliationDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAffiliationDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAffiliationDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Faculty(string FacultyName, string RegistrationNo, string AadhaarNo, string CollegeID, string DepartmentID, string Designation, string Address, string City, string State, string Gender, string Dob, string MobileNo, string Email, string Pincode, string Type) {
            base.Channel.Faculty(FacultyName, RegistrationNo, AadhaarNo, CollegeID, DepartmentID, Designation, Address, City, State, Gender, Dob, MobileNo, Email, Pincode, Type);
        }
    }
}
