//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpCode { get; set; }
        public string EmpDesignation { get; set; }
        public Nullable<System.DateTime> EmpDob { get; set; }
        public string EmpGender { get; set; }
        public string EmpAddress { get; set; }
        public string EmpCity { get; set; }
        public string EmpState { get; set; }
        public string EmpPincode { get; set; }
        public string EmpMobile { get; set; }
        public string EmpEmail { get; set; }
        public string EmpPunchID { get; set; }
        public string EmpAadharNo { get; set; }
        public Nullable<System.DateTime> EmpCreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> SuccessTransCount { get; set; }
        public Nullable<int> FailedTransCount { get; set; }
        public short EmpIsActive { get; set; }
        public Nullable<int> EmpUserID { get; set; }
        public Nullable<int> EmpDeptID { get; set; }
        public Nullable<int> EmpBrnID { get; set; }
        public Nullable<System.DateTime> EmpJoiningDate { get; set; }
        public int EmpShiftID { get; set; }
        public string WeekDays { get; set; }
        public int Location { get; set; }
        public int MastriID { get; set; }
        public Nullable<int> Roll { get; set; }
        public string ReportID { get; set; }
        public Nullable<int> Collegeid { get; set; }
        public Nullable<short> FacultyStatus { get; set; }
        public string DepartmentName { get; set; }
        public string Specialization { get; set; }
        public int SpecializationID { get; set; }
        public Nullable<short> EmpType { get; set; }
        public Nullable<short> VerifyFlag { get; set; }
        public Nullable<short> ColorStatus { get; set; }
    }
}
