//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_direct_principal_experience
    {
        public int id { get; set; }
        public int activityid { get; set; }
        public Nullable<int> collegeid { get; set; }
        public string registrationnumber { get; set; }
        public bool presentlyworking { get; set; }
        public string workinginstitutionorganisationname { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public Nullable<int> facultydesignationid { get; set; }
        public string facultydesignation { get; set; }
        public string supportingdocs1 { get; set; }
        public string supportingdocs2 { get; set; }
        public string supportingdocs3 { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isactive { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
        public Nullable<System.DateTime> updatedby { get; set; }
        public Nullable<int> updatedon { get; set; }
    }
}
