//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_noc_mergecourse
    {
        public int id { get; set; }
        public int academicyearId { get; set; }
        public int nocid { get; set; }
        public int noctypeid { get; set; }
        public int parentspecid { get; set; }
        public Nullable<int> parentapprovedintake { get; set; }
        public int childspecid { get; set; }
        public Nullable<int> childapprovedintake { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
