//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_students_complaints
    {
        public int id { get; set; }
        public int academicyearId { get; set; }
        public string TicketId { get; set; }
        public int collegeId { get; set; }
        public int complaintId { get; set; }
        public string otherComplaint { get; set; }
        public System.DateTime complaintDate { get; set; }
        public string complaintDescription { get; set; }
        public Nullable<int> complaintStatus { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string IdProof { get; set; }
        public string ParentOrGuardiansname { get; set; }
        public string ParentOrGuardiansmobile { get; set; }
        public Nullable<int> courseStudiedId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> yearofStudy { get; set; }
        public Nullable<bool> replayStatus { get; set; }
        public Nullable<System.DateTime> replayDate { get; set; }
        public string complaintFile { get; set; }
        public string Name { get; set; }
        public string HallticketNo { get; set; }
        public int Gender { get; set; }
        public System.DateTime Dateofbirth { get; set; }
        public string replayFile { get; set; }
        public Nullable<int> nooftimes { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    }
}
