//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_registered_faculty_edit_fileds
    {
        public int id { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<bool> RegistrationNumber { get; set; }
        public Nullable<bool> FirstName { get; set; }
        public Nullable<bool> MiddleName { get; set; }
        public Nullable<bool> LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> FatherOrHusbandName { get; set; }
        public Nullable<bool> MotherName { get; set; }
        public Nullable<bool> DateOfBirth { get; set; }
        public Nullable<bool> OrganizationName { get; set; }
        public Nullable<bool> Designation { get; set; }
        public Nullable<bool> OtherDesignation { get; set; }
        public Nullable<bool> Department { get; set; }
        public Nullable<bool> OtherDepartment { get; set; }
        public Nullable<bool> grosssalary { get; set; }
        public Nullable<bool> DateOfAppointment { get; set; }
        public Nullable<bool> ProceedingsNumber { get; set; }
        public Nullable<bool> ProceedingDocument { get; set; }
        public Nullable<bool> AICTEFacultyId { get; set; }
        public Nullable<bool> TotalExperience { get; set; }
        public Nullable<bool> TotalExperiencePresentCollege { get; set; }
        public Nullable<bool> PANNumber { get; set; }
        public Nullable<bool> AadhaarNumber { get; set; }
        public Nullable<bool> Mobile { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> National { get; set; }
        public Nullable<bool> InterNational { get; set; }
        public Nullable<bool> Citation { get; set; }
        public Nullable<bool> Awards { get; set; }
        public Nullable<bool> Photo { get; set; }
        public Nullable<bool> PANDocument { get; set; }
        public Nullable<bool> AadhaarDocument { get; set; }
        public Nullable<bool> IncometaxDocument { get; set; }
        public Nullable<bool> CourseStudied { get; set; }
        public Nullable<bool> Branch_Specialization { get; set; }
        public Nullable<bool> YearofPassing { get; set; }
        public Nullable<bool> Marks { get; set; }
        public Nullable<bool> Division { get; set; }
        public Nullable<bool> University { get; set; }
        public Nullable<bool> Place { get; set; }
        public Nullable<bool> Certificate { get; set; }
        public Nullable<bool> Mphil_edit { get; set; }
        public Nullable<bool> Phd_edit { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    }
}
