//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_facultydeclaration
    {
        public int sno { get; set; }
        public int FacultyId { get; set; }
        public short FacultyType { get; set; }
        public short AccademicYear { get; set; }
        public string designation { get; set; }
        public string department { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public Nullable<System.DateTime> Dateofjoining { get; set; }
        public Nullable<System.DateTime> DateofReleving { get; set; }
        public Nullable<int> NewCollegeId { get; set; }
        public Nullable<System.DateTime> NewCollegeJoiningDate { get; set; }
        public Nullable<System.DateTime> Newcollegerelevingdate { get; set; }
        public string Reason { get; set; }
        public string declaration { get; set; }
        public System.DateTime createdon { get; set; }
        public int Createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<short> Isactive { get; set; }
    }
}
