//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_intake_adjustmentsdata
    {
        public int Id { get; set; }
        public int adjustmentid { get; set; }
        public int adjustmentspecializationid { get; set; }
        public int adjustmentintake { get; set; }
        public Nullable<short> adjustedcoursestatus { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
        public int isactive { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
