//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_ug_students
    {
        public int id { get; set; }
        public string studentsname { get; set; }
        public string HTNo { get; set; }
        public string AadhaarNumber { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public string Department { get; set; }
        public Nullable<int> departmentid { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> CillegeId { get; set; }
    }
}
