//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_extracurricularactivities
    {
        public int sno { get; set; }
        public string activityname { get; set; }
        public int activitytype { get; set; }
        public string activitydescription { get; set; }
        public string activitytypedescription { get; set; }
        public Nullable<int> activityorder { get; set; }
        public bool isactive { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
    }
}
