//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_accounts_payment_type
    {
        public jntuh_college_accounts_payment_type()
        {
            this.jntuh_college_dd_payments = new HashSet<jntuh_college_dd_payments>();
        }
    
        public int Id { get; set; }
        public string Payment_type { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<jntuh_college_dd_payments> jntuh_college_dd_payments { get; set; }
    }
}
