//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_pgstudent_projectdetatails
    {
        public int ID { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public int CollegeId { get; set; }
        public Nullable<bool> ProjectEnroll { get; set; }
        public string StudentsName { get; set; }
        public string HallticketNumber { get; set; }
        public string DeptName { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> NumOfReviews { get; set; }
        public string ReviewedWeeks { get; set; }
        public string InternalGuideRegNumber { get; set; }
        public string InternalGuideName { get; set; }
        public Nullable<int> InternalGuideDesignation { get; set; }
        public Nullable<int> InternalguideDepartment { get; set; }
        public string InternalguideEmail { get; set; }
        public string ExternalGuideName { get; set; }
        public Nullable<int> ExternalGuideDesignation { get; set; }
        public string ExternalEmail { get; set; }
        public string ExternalQualification { get; set; }
        public Nullable<int> ExternalExperience { get; set; }
        public string ExternalOrgName { get; set; }
        public string ExternalOrgAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string reason { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual jntuh_department jntuh_department { get; set; }
        public virtual jntuh_designation jntuh_designation { get; set; }
        public virtual jntuh_designation jntuh_designation1 { get; set; }
    }
}
