//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_academic_year
    {
        public jntuh_academic_year()
        {
            this.jntuh_college_nbaaccreditationdata = new HashSet<jntuh_college_nbaaccreditationdata>();
            this.jntuh_college_staticdata_modifications = new HashSet<jntuh_college_staticdata_modifications>();
            this.jntuh_approvedadmitted_intake = new HashSet<jntuh_approvedadmitted_intake>();
            this.jntuh_college_academic_performance = new HashSet<jntuh_college_academic_performance>();
            this.jntuh_college_affiliation = new HashSet<jntuh_college_affiliation>();
            this.jntuh_college_batch_performance = new HashSet<jntuh_college_batch_performance>();
            this.jntuh_college_booksandjournals = new HashSet<jntuh_college_booksandjournals>();
            this.jntuh_college_dd_payments = new HashSet<jntuh_college_dd_payments>();
            this.jntuh_college_enclosures = new HashSet<jntuh_college_enclosures>();
            this.jntuh_college_faculty_information = new HashSet<jntuh_college_faculty_information>();
            this.jntuh_college_facultyverification_tracking = new HashSet<jntuh_college_facultyverification_tracking>();
            this.jntuh_college_financialstandards = new HashSet<jntuh_college_financialstandards>();
            this.jntuh_college_intake_existing = new HashSet<jntuh_college_intake_existing>();
            this.jntuh_college_intake_proposed = new HashSet<jntuh_college_intake_proposed>();
            this.jntuh_college_placement = new HashSet<jntuh_college_placement>();
            this.jntuh_college_selfappraisal = new HashSet<jntuh_college_selfappraisal>();
            this.jntuh_college_women_protection_cell_rti_antiragging_details = new HashSet<jntuh_college_women_protection_cell_rti_antiragging_details>();
            this.jntuh_college_womenprotection_antiragging_complaints = new HashSet<jntuh_college_womenprotection_antiragging_complaints>();
            this.jntuh_inspection_phase = new HashSet<jntuh_inspection_phase>();
            this.jntuh_paymentrequests = new HashSet<jntuh_paymentrequests>();
            this.jntuh_paymentresponse = new HashSet<jntuh_paymentresponse>();
            this.jntuh_college_links_assigned = new HashSet<jntuh_college_links_assigned>();
        }
    
        public int id { get; set; }
        public string academicYear { get; set; }
        public int actualYear { get; set; }
        public bool isPresentAcademicYear { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual ICollection<jntuh_college_nbaaccreditationdata> jntuh_college_nbaaccreditationdata { get; set; }
        public virtual ICollection<jntuh_college_staticdata_modifications> jntuh_college_staticdata_modifications { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual ICollection<jntuh_approvedadmitted_intake> jntuh_approvedadmitted_intake { get; set; }
        public virtual ICollection<jntuh_college_academic_performance> jntuh_college_academic_performance { get; set; }
        public virtual ICollection<jntuh_college_affiliation> jntuh_college_affiliation { get; set; }
        public virtual ICollection<jntuh_college_batch_performance> jntuh_college_batch_performance { get; set; }
        public virtual ICollection<jntuh_college_booksandjournals> jntuh_college_booksandjournals { get; set; }
        public virtual ICollection<jntuh_college_dd_payments> jntuh_college_dd_payments { get; set; }
        public virtual ICollection<jntuh_college_enclosures> jntuh_college_enclosures { get; set; }
        public virtual ICollection<jntuh_college_faculty_information> jntuh_college_faculty_information { get; set; }
        public virtual ICollection<jntuh_college_facultyverification_tracking> jntuh_college_facultyverification_tracking { get; set; }
        public virtual ICollection<jntuh_college_financialstandards> jntuh_college_financialstandards { get; set; }
        public virtual ICollection<jntuh_college_intake_existing> jntuh_college_intake_existing { get; set; }
        public virtual ICollection<jntuh_college_intake_proposed> jntuh_college_intake_proposed { get; set; }
        public virtual ICollection<jntuh_college_placement> jntuh_college_placement { get; set; }
        public virtual ICollection<jntuh_college_selfappraisal> jntuh_college_selfappraisal { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell_rti_antiragging_details> jntuh_college_women_protection_cell_rti_antiragging_details { get; set; }
        public virtual ICollection<jntuh_college_womenprotection_antiragging_complaints> jntuh_college_womenprotection_antiragging_complaints { get; set; }
        public virtual ICollection<jntuh_inspection_phase> jntuh_inspection_phase { get; set; }
        public virtual ICollection<jntuh_paymentrequests> jntuh_paymentrequests { get; set; }
        public virtual ICollection<jntuh_paymentresponse> jntuh_paymentresponse { get; set; }
        public virtual ICollection<jntuh_college_links_assigned> jntuh_college_links_assigned { get; set; }
    }
}
