//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_jntu_pci_aicte_intakes
    {
        public int id { get; set; }
        public int acedamicyearid { get; set; }
        public string acedamicyears { get; set; }
        public int collegeid { get; set; }
        public int degree { get; set; }
        public int department { get; set; }
        public int specialization { get; set; }
        public int jntuh { get; set; }
        public Nullable<int> pci { get; set; }
        public Nullable<int> aicte { get; set; }
        public bool isactive { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
