//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_faculty_phddetails
    {
        public int Id { get; set; }
        public int Facultyid { get; set; }
        public string Hallticketnumber { get; set; }
        public int Phdtype { get; set; }
        public Nullable<int> Phdawardyear { get; set; }
        public string University { get; set; }
        public string Placeofuniversity { get; set; }
        public Nullable<int> Universitytype { get; set; }
        public string Phdtitle { get; set; }
        public string Admissionletter { get; set; }
        public string Prephdletter { get; set; }
        public string Supervisorname1 { get; set; }
        public string Supervisorname2 { get; set; }
        public string Supervisorname3 { get; set; }
        public string Thesiscoverpage { get; set; }
        public string Thesis { get; set; }
        public string Phdod { get; set; }
        public string Genuinenessletter { get; set; }
        public string Collegeauthaticationletter { get; set; }
        public string Otherletter { get; set; }
        public Nullable<bool> Phdstatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Isapproved { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string Nocletter { get; set; }
        public int Notificationissued { get; set; }
        public Nullable<int> Reviewsattended { get; set; }
        public Nullable<int> Paperspublished { get; set; }
        public Nullable<int> PaperspublishedDPW { get; set; }
        public string Timeofdefense { get; set; }
        public Nullable<System.DateTime> Vivadate { get; set; }
        public string Boschairperson { get; set; }
        public Nullable<System.DateTime> Pressnotification { get; set; }
        public Nullable<bool> Convocationattended { get; set; }
        public string Department { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> IntNationalJrnls { get; set; }
        public Nullable<int> NationalJrnls { get; set; }
        public string IntNationalJrnlsDocLetter { get; set; }
        public string NationalJrnlsDocLetter { get; set; }
        public Nullable<int> IntNationalCnfrns { get; set; }
        public Nullable<int> NationalCnfrns { get; set; }
        public string IntNationalCnfrnsLetter { get; set; }
        public string NationalCnfrnsLetter { get; set; }
        public Nullable<int> AdmissionYear { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<System.DateTime> IsSubmittedDate { get; set; }
    }
}
