//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_minoritystatus
    {
        public int id { get; set; }
        public int academicYearid { get; set; }
        public int collegeId { get; set; }
        public int collegeStatusid { get; set; }
        public Nullable<System.DateTime> statusFromdate { get; set; }
        public Nullable<System.DateTime> statusTodate { get; set; }
        public string statusFile { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_college_status jntuh_college_status { get; set; }
    }
}
