//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_paymentrequests
    {
        public long Id { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public string CollegeCode { get; set; }
        public string ChallanNumber { get; set; }
        public System.DateTime TxnDate { get; set; }
        public string MerchantID { get; set; }
        public string CustomerID { get; set; }
        public decimal TxnAmount { get; set; }
        public string CurrencyType { get; set; }
        public string SecurityID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> noctypeId { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual jntuh_college_paymentoffee_type jntuh_college_paymentoffee_type { get; set; }
    }
}
