//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_links_assigned
    {
        public int id { get; set; }
        public Nullable<int> linkId { get; set; }
        public int academicyearId { get; set; }
        public int phaseId { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> isAssigned { get; set; }
        public Nullable<bool> isSCMupload { get; set; }
        public Nullable<System.DateTime> scmuploadtodate { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
    }
}
