//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_principal_details_affiliated_colleges
    {
        public int id { get; set; }
        public string collegetype { get; set; }
        public int academicyearid { get; set; }
        public int collegeid { get; set; }
        public string registrationnumber { get; set; }
        public int ugdivision { get; set; }
        public int ugpassedyear { get; set; }
        public string ugodproof { get; set; }
        public int pgdivision { get; set; }
        public int pgpassedyear { get; set; }
        public string pgodproof { get; set; }
        public int phddivision { get; set; }
        public int phdpassedyear { get; set; }
        public string phdodproof { get; set; }
        public decimal lecturernoofyears { get; set; }
        public string lecturersupportingdocument { get; set; }
        public decimal associateprofnoofyears { get; set; }
        public string associateprofsupportingdoc { get; set; }
        public decimal professornoofyears { get; set; }
        public string professorsupportingdoc { get; set; }
        public decimal principalnoofyears { get; set; }
        public string principalsupportingdoc { get; set; }
        public decimal researchnoofyears { get; set; }
        public string researchsupportingdoc { get; set; }
        public decimal industrynoofyears { get; set; }
        public string industrysupportingdoc { get; set; }
        public decimal totalexperience { get; set; }
        public Nullable<decimal> internationaljournals { get; set; }
        public string internationaljournalsdoc { get; set; }
        public Nullable<decimal> internationalconferences { get; set; }
        public string internationalconferencesdoc { get; set; }
        public Nullable<decimal> nationaljournals { get; set; }
        public string nationaljournalsdoc { get; set; }
        public Nullable<decimal> nationalconferences { get; set; }
        public string nationalconferencesdoc { get; set; }
        public Nullable<decimal> totalpublications { get; set; }
        public Nullable<decimal> supervisorphdguided { get; set; }
        public string supervisorphdguideddoc { get; set; }
        public Nullable<decimal> cosupervisorphdguided { get; set; }
        public string cosupervisorphdguideddoc { get; set; }
        public Nullable<decimal> totalphdsguided { get; set; }
        public string supervisorguideduniversity { get; set; }
        public string cosupervisorguideduniversity { get; set; }
        public string assistantprofratactivitystatus { get; set; }
        public Nullable<System.DateTime> assistantprofratifieddate { get; set; }
        public Nullable<decimal> assistantprofratnoofyears { get; set; }
        public string assistantprofratsuptdoc { get; set; }
        public string associateprofratactivitystatus { get; set; }
        public Nullable<System.DateTime> associateprofratifieddate { get; set; }
        public Nullable<decimal> associateprofratnoofyears { get; set; }
        public string associateprofratsuptdoc { get; set; }
        public string professorratactivitystatus { get; set; }
        public Nullable<System.DateTime> professorratifieddate { get; set; }
        public Nullable<decimal> professorratnoofyears { get; set; }
        public string professorratsuptdoc { get; set; }
        public string principalratactivitystatus { get; set; }
        public Nullable<System.DateTime> principalratifieddate { get; set; }
        public Nullable<decimal> principalratnoofyears { get; set; }
        public string principalratsuptdoc { get; set; }
        public Nullable<decimal> totalratifiedservice { get; set; }
        public string ugdegree { get; set; }
        public string pgdegree { get; set; }
        public string phddegree { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
