//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_ugstudents
    {
        public int id { get; set; }
        public int academicyearid { get; set; }
        public int collegeid { get; set; }
        public string estudentname { get; set; }
        public Nullable<System.DateTime> examdob { get; set; }
        public string eaadhaarno { get; set; }
        public string hallticketno { get; set; }
        public Nullable<int> specializationid { get; set; }
        public short gender { get; set; }
        public string mobileno { get; set; }
        public string emailid { get; set; }
        public string aadhaarno { get; set; }
        public string studentname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string aadhaardoc { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
