//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_faculty_information
    {
        public int id { get; set; }
        public int academicyear { get; set; }
        public int collegeid { get; set; }
        public int degree { get; set; }
        public int staff { get; set; }
        public int student { get; set; }
        public int numberoffacultyonrole { get; set; }
        public int numberoffacultyterminatedorregined { get; set; }
        public bool payscaleimplemented { get; set; }
        public string asstprofpayscale { get; set; }
        public string asstprofpay { get; set; }
        public string assocprofpayscale { get; set; }
        public string assocprofpay { get; set; }
        public string profpayscale { get; set; }
        public string profpays { get; set; }
        public Nullable<decimal> retentionpercentage { get; set; }
        public Nullable<bool> oppurtunities { get; set; }
        public Nullable<bool> isactive { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual jntuh_college jntuh_college { get; set; }
    }
}
