//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_registered_faculty_experience_log
    {
        public int Id { get; set; }
        public int facultyId { get; set; }
        public Nullable<int> collegeId { get; set; }
        public string OtherCollege { get; set; }
        public Nullable<int> facultyDesignationId { get; set; }
        public string OtherDesignation { get; set; }
        public Nullable<System.DateTime> facultyDateOfAppointment { get; set; }
        public Nullable<System.DateTime> facultyDateOfResignation { get; set; }
        public string facultyRelievingLetter { get; set; }
        public string facultyJoiningOrder { get; set; }
        public string facultySalary { get; set; }
        public string FacultySCMDocument { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual jntuh_designation jntuh_designation { get; set; }
        public virtual jntuh_registered_faculty jntuh_registered_faculty { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
