//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_basreport
    {
        public int Id { get; set; }
        public int collegeId { get; set; }
        public int type { get; set; }
        public string RegistrationNumber { get; set; }
        public string name { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> monthId { get; set; }
        public string month { get; set; }
        public Nullable<System.DateTime> joiningDate { get; set; }
        public Nullable<int> totalworkingDays { get; set; }
        public Nullable<int> NoofHolidays { get; set; }
        public Nullable<int> NoofPresentDays { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
    }
}
