//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_generated_letters
    {
        public int id { get; set; }
        public string letterCode { get; set; }
        public string lettercodeDescription { get; set; }
        public string letterSubject { get; set; }
        public string letterReference { get; set; }
        public Nullable<bool> isRef { get; set; }
        public string letterDescription { get; set; }
        public string letterNote { get; set; }
        public Nullable<System.DateTime> letterGeneratedDate { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    }
}
