//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_oladcolleges
    {
        public int sno { get; set; }
        public string collegecode { get; set; }
        public string collegename { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public Nullable<int> yearofestablishment { get; set; }
        public Nullable<int> yearofclosing { get; set; }
        public string website { get; set; }
        public string collegestatus { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> createdby { get; set; }
    }
}
