//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_noc_data
    {
        public int id { get; set; }
        public int academicyearId { get; set; }
        public int collegeId { get; set; }
        public int noctypeId { get; set; }
        public int departmentId { get; set; }
        public int specializationId { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> approvedIntake { get; set; }
        public Nullable<bool> isClosure { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    }
}
