//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_academic_data
    {
        public int Id { get; set; }
        public int accademicyaerid { get; set; }
        public int collegeid { get; set; }
        public int degreeid { get; set; }
        public int departmentid { get; set; }
        public int specealizationId { get; set; }
        public Nullable<int> degreeyear { get; set; }
        public int semister { get; set; }
        public string supportingdocument { get; set; }
        public Nullable<bool> isactive { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
