//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_student
    {
        public int sid { get; set; }
        public int AcademicYearid { get; set; }
        public int collegeid { get; set; }
        public string studentname { get; set; }
        public string hallticketnum { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public Nullable<int> degreeid { get; set; }
        public string AadhaarNumber { get; set; }
        public string AadhaarDocument { get; set; }
        public bool Status { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Reason { get; set; }
        public string StudentYear { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual jntuh_department jntuh_department { get; set; }
        public virtual jntuh_specialization jntuh_specialization { get; set; }
        public virtual jntuh_shift jntuh_shift { get; set; }
        public virtual jntuh_degree jntuh_degree { get; set; }
    }
}
