//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_faculty_news
    {
        public int id { get; set; }
        public bool isNews { get; set; }
        public Nullable<int> facultyId { get; set; }
        public string title { get; set; }
        public string navigateURL { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isLatest { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual jntuh_registered_faculty jntuh_registered_faculty { get; set; }
    }
}
