//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_governingbodydesignations
    {
        public int id { get; set; }
        public string designation { get; set; }
        public System.DateTime createdon { get; set; }
        public bool isactive { get; set; }
    }
}
