//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_faculty_edit_requests
    {
        public int id { get; set; }
        public int academicYearId { get; set; }
        public string TicketId { get; set; }
        public int facultyId { get; set; }
        public int fieldId { get; set; }
        public string requestReason { get; set; }
        public string supportingDocs { get; set; }
        public Nullable<short> isApproved { get; set; }
        public string rejectReason { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> deactivatedOn { get; set; }
        public Nullable<int> deactivatedBy { get; set; }
    }
}
