//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_womenprotection_antiragging_complaints
    {
        public int id { get; set; }
        public int collegeId { get; set; }
        public int academicyear { get; set; }
        public int complainttype { get; set; }
        public string complaintgivenbyregnum { get; set; }
        public string complaintgivenbyname { get; set; }
        public string complaintonregnum { get; set; }
        public string complaintonname { get; set; }
        public string complaintdescription { get; set; }
        public string complaintsupportingdoc { get; set; }
        public string actiontaken { get; set; }
        public string actiontakensupportingdoc { get; set; }
        public bool isactive { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual jntuh_college jntuh_college { get; set; }
    }
}
