//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_bas_complaints
    {
        public int id { get; set; }
        public int academicyearId { get; set; }
        public int collegeid { get; set; }
        public string Name { get; set; }
        public string registrationnumber { get; set; }
        public Nullable<int> complainttype { get; set; }
        public string complaint { get; set; }
        public string supportdoc { get; set; }
        public string complaintid { get; set; }
        public Nullable<System.DateTime> complaintdate { get; set; }
        public Nullable<bool> replaystatus { get; set; }
        public string Replay { get; set; }
        public Nullable<System.DateTime> replaydate { get; set; }
        public Nullable<int> complaintstatus { get; set; }
        public string complaintgivenby { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> cretaedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
