//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_intake_adjustments
    {
        public int Id { get; set; }
        public int aicteapprovedId { get; set; }
        public int collegeId { get; set; }
        public Nullable<int> academicyearId { get; set; }
        public int specalizationid { get; set; }
        public short coursestaus { get; set; }
        public Nullable<short> adjustmentstatus { get; set; }
        public int aicteintake { get; set; }
        public Nullable<int> adjustedintake { get; set; }
        public Nullable<int> remaningintake { get; set; }
        public System.DateTime createdon { get; set; }
        public int createdby { get; set; }
        public short isactive { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
