//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_apistudentspush_data
    {
        public int Id { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public string AadhaarNo { get; set; }
        public string StudentHallTicketNo { get; set; }
        public string StudentName { get; set; }
        public string Gender { get; set; }
        public string Branch { get; set; }
        public string StudentStatus { get; set; }
        public string ApiStatus { get; set; }
        public string GeneratedAttendeeId { get; set; }
        public string ResponseMsg { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
