//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_attendace
    {
        public int Id { get; set; }
        public Nullable<double> Collegeid { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public string CollegeCode { get; set; }
        public Nullable<double> EmpDeptID { get; set; }
        public string RegistrationNo { get; set; }
        public string Month { get; set; }
        public string ONE { get; set; }
        public string TWO { get; set; }
        public string THREE { get; set; }
        public string FOUR { get; set; }
        public string FIVE { get; set; }
        public string SIX { get; set; }
        public string SEVEN { get; set; }
        public string EAIGHT { get; set; }
        public string NINE { get; set; }
        public string TEN { get; set; }
        public string ELEVEN { get; set; }
        public string TWELVE { get; set; }
        public string THIRTEEN { get; set; }
        public string FOURTEEN { get; set; }
        public string FIFGHTEEN { get; set; }
        public string SIXTEEN { get; set; }
        public string SEVENGHTEEN { get; set; }
        public string EAIGHTEEN { get; set; }
        public string NINGHTEEN { get; set; }
        public string TWENTY { get; set; }
        public string TWENTY_ONE { get; set; }
        public string TWENTY_TWO { get; set; }
        public string TWENTY_THREE { get; set; }
        public string TWENTY_FOUR { get; set; }
        public string TWENTY_FIVE { get; set; }
        public string TWENTY_SIX { get; set; }
        public string TWENTY_SEVEN { get; set; }
        public string TWEENTY_EAIGHT { get; set; }
        public string TWENTY_NINE { get; set; }
        public string THIRTY { get; set; }
        public string THIRTY_ONE { get; set; }
        public Nullable<double> TotalPercentage { get; set; }
    }
}
