//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_afrc_fee
    {
        public int Id { get; set; }
        public Nullable<int> academicyearId { get; set; }
        public int collegeId { get; set; }
        public Nullable<int> groupofInstitutionsafrcFee { get; set; }
        public int afrcFee { get; set; }
    }
}
