//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_courtcases
    {
        public int id { get; set; }
        public int collegeid { get; set; }
        public string wporslorotherno { get; set; }
        public int yearoffilling { get; set; }
        public string prayerofthepetitioner { get; set; }
        public Nullable<int> respondents { get; set; }
        public string wppetitionerdocument { get; set; }
        public string ordercopy { get; set; }
        public string intermorder { get; set; }
        public string remarks { get; set; }
        public bool isactive { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
    }
}
