//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_governingbody
    {
        public int id { get; set; }
        public int academicyearid { get; set; }
        public int collegeid { get; set; }
        public string nameofthemember { get; set; }
        public short memberdesignation { get; set; }
        public string organizationworking { get; set; }
        public string organizationdesignation { get; set; }
        public Nullable<System.DateTime> dateofappointment { get; set; }
        public string supportingdocument { get; set; }
        public string supportingdocument1 { get; set; }
        public System.DateTime createdon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public bool isactive { get; set; }
    }
}
