//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_grievancesassigned
    {
        public int id { get; set; }
        public int College_facultyid { get; set; }
        public int grievanceassiegnedto { get; set; }
        public int Grievancetype { get; set; }
        public int Grievanceid { get; set; }
        public Nullable<int> Subgrievanceid { get; set; }
        public string Ticketid { get; set; }
        public Nullable<int> Ticketstatus { get; set; }
        public string Collegeletter { get; set; }
        public string Collegesupportingdocument { get; set; }
        public string CollegeRemarks { get; set; }
        public string adminremarks { get; set; }
        public Nullable<int> ticketclosedby { get; set; }
        public Nullable<System.DateTime> ticketclosedon { get; set; }
        public System.DateTime admincreatedon { get; set; }
        public int admincreatedby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> createdby { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> adminupdatedon { get; set; }
        public Nullable<int> adminupdatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
