//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_facultyverification_tracking
    {
        public int Id { get; set; }
        public int academicyearId { get; set; }
        public int collegeId { get; set; }
        public string registrationNumber { get; set; }
        public Nullable<bool> NotQualifiedAsperAICTE { get; set; }
        public Nullable<bool> IncompleteCertificates { get; set; }
        public Nullable<bool> Xeroxcopyofcertificates { get; set; }
        public Nullable<bool> InvalidPANNumber { get; set; }
        public Nullable<bool> NoRelevantUG { get; set; }
        public Nullable<bool> NoRelevantPG { get; set; }
        public Nullable<bool> NoRelevantPHD { get; set; }
        public Nullable<bool> NoSCM { get; set; }
        public Nullable<bool> BasFlag { get; set; }
        public Nullable<bool> Absent { get; set; }
        public Nullable<bool> Blacklistfaculy { get; set; }
        public Nullable<bool> AadhaarFlag { get; set; }
        public Nullable<bool> VerificationStatus { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> deactivatedOn { get; set; }
        public Nullable<int> deactivatedBy { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual jntuh_college jntuh_college { get; set; }
    }
}
