//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_collegefaculty_leaves
    {
        public int id { get; set; }
        public int academicYearId { get; set; }
        public int collegeId { get; set; }
        public string RegistrationNumber { get; set; }
        public System.DateTime leavefromdate { get; set; }
        public System.DateTime leavetodate { get; set; }
        public int leavetypeid { get; set; }
        public string document { get; set; }
        public int noofdays { get; set; }
        public bool approvedStatus { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
