//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_timetables
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public int DegreeId { get; set; }
        public int DepartmentId { get; set; }
        public int SpecializationId { get; set; }
        public int AcademicyearId { get; set; }
        public int Year { get; set; }
        public int Semister { get; set; }
        public bool IsActive { get; set; }
        public string Path { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
