//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_dd_payments
    {
        public int Id { get; set; }
        public int AcademicYearId { get; set; }
        public int collegeId { get; set; }
        public int FeeTypeId { get; set; }
        public int Sub_PurposeId { get; set; }
        public string DepartmentsIds { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public int BankId { get; set; }
        public int PaymentTypeId { get; set; }
        public string Tranaction_Number { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual jntuh_college_accounts_payment_type jntuh_college_accounts_payment_type { get; set; }
        public virtual jntuh_college_paymentoffee_type jntuh_college_paymentoffee_type { get; set; }
        public virtual jntuh_college_payments_subpurpose jntuh_college_payments_subpurpose { get; set; }
        public virtual jntuh_college_payments_banks jntuh_college_payments_banks { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
