//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_paymentresponse
    {
        public long Id { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public string CollegeId { get; set; }
        public string MerchantID { get; set; }
        public string CustomerID { get; set; }
        public string TxnReferenceNo { get; set; }
        public string BankReferenceNo { get; set; }
        public decimal TxnAmount { get; set; }
        public string BankID { get; set; }
        public string BankMerchantID { get; set; }
        public string TxnType { get; set; }
        public string CurrencyName { get; set; }
        public System.DateTime TxnDate { get; set; }
        public string AuthStatus { get; set; }
        public string ErrorStatus { get; set; }
        public string ErrorDescription { get; set; }
        public string SettlementType { get; set; }
        public string ChallanNumber { get; set; }
        public int PaymentTypeID { get; set; }
        public Nullable<int> noctypeId { get; set; }
    
        public virtual jntuh_academic_year jntuh_academic_year { get; set; }
        public virtual jntuh_college_paymentoffee_type jntuh_college_paymentoffee_type { get; set; }
    }
}
